FROM apache/airflow:3.1.5

USER root
RUN apt-get update && apt-get install -y --no-install-recommends build-essential && apt-get clean && rm -rf /var/lib/apt/lists/*

USER airflow
COPY requirements-airflow.txt /requirements-airflow.txt
RUN python -m pip install --no-cache-dir -r /requirements-airflow.txt